### ISSUE TITLE
Hi Guys, have you seen this issue before?

### ISSUE THREAD

**Issue by mikeblakeuk** [ekoshkin/teamcity-azure-active-directory#10]
Additional technical information:
Correlation ID: eee80151-6e99-4231-xxx
Timestamp: 2015-08-17 11:17:01Z
AADSTS90013: Invalid input received from the user.

**Comment by ekoshkin** [comment]
Nope, what MS guys are saying about it?

**Comment by maartenba** [comment]
Having the same issue here. Can you ping me on Skype whenever you're online?

**Comment by mikeblakeuk** [comment]
https://login.microsoftonline.com/common/oauth2/authorize&response_type... should be https://login.microsoftonline.com/common/oauth2/authorize?response_type...

https://msdn.microsoft.com/en-gb/library/azure/dn645542.aspx

**Comment by ekoshkin** [comment]
Looks like App Auth 2.0 Authorization endpoint format was changed on Azure Portal side.
