### ISSUE TITLE
No login or user created after redirect

### ISSUE THREAD

**Issue by yesman85** [ekoshkin/teamcity-azure-active-directory#16]
I setup the plugin (I think correctly), but when I click the login with Azure link on the TC login page it will redirect me to the Azure login page, lets me login, but then it goes back to the TC login page again.

I also see no user has been added to the TC users list.

**Comment by ekoshkin** [comment]
please provide teamcity server logs

**Comment by yesman85** [comment]
I shut down TC, removed all log files, started it up again, and tried to login with Azure. Attached are all found logs with debug-auth enabled.

[teamcity-auth.txt](https://github.com/ekoshkin/teamcity-azure-active-directory/files/96349/teamcity-auth.txt)

**Comment by yesman85** [comment]
I looked at the logs and it seems to work now. I had set the Reply Url to login.html instead of overview.html.
