### ISSUE TITLE
Please add an OSS license

### ISSUE THREAD

**Issue by DamianEdwards** [ekoshkin/teamcity-azure-active-directory#9]
Having a OSS license stated in the root of your repo (e.g. LICENSE.txt) will help many people who need an explicit license statement before being able to look at, use, or contribute to code due to corporate policy (as is true in my case :smile:).

I recommend using http://choosealicense.com/ to help with this.

**Comment by anurse** [comment]
Big :+1: !

**Comment by ekoshkin** [comment]
done
http://choosealicense.com/ - nice site by the way, thank you!
